### ISSUE TITLE
Export error when no start or end date is set

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-reports#105]
### Description

Originally opened this issue here: https://github.com/barrelstrength/craft-sprout-base-reports/issues/15 as this is where the error is coming from.

When you don't set a start and end date on a report, when exporting this will throw a PHP error:

```
Error: Call to a member function setTimezone() on bool in /srv/app/nttmcoll-stagec3/htdocs/vendor/barrelstrength/sprout-base-reports/src/services/Reports.php:185
Stack trace:
#0 /srv/app/nttmcoll-stagec3/htdocs/vendor/barrelstrength/sprout-base-reports/src/elements/Report.php(529): barrelstrength\sproutbasereports\services\Reports->getUtcDateTime(Array)
#1 /srv/app/nttmcoll-stagec3/htdocs/vendor/barrelstrength/sprout-forms/src/integrations/sproutreports/datasources/EntriesDataSource.php(86): barrelstrength\sproutbasereports\elements\Report->getStartEndDate()
#2 /srv/app/nttmcoll-stagec3/htdocs/vendor/barrelstrength/sprout-base-reports/src/controllers/ReportsController.php(492): barrelstrength\sproutforms\integrations\sproutreports\datasources\EntriesDataSource->getResults(Object(barrelstrength\sproutbasereports\elements\Report), Array)
#3 [internal function]: barrelstrength\sproutbasereports\controllers\ReportsController->actionExportReport()
#4 /srv/app/nttmcoll-stagec3/htdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /srv/app/nttmcoll-stagec3/htdocs/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#6 /srv/app/nttmcoll-stagec3/htdocs/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('export-report', Array)
#7 /srv/app/nttmcoll-stagec3/htdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('export-report', Array)
#8 /srv/app/nttmcoll-stagec3/htdocs/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('sprout-base-rep...', Array)
#9 /srv/app/nttmcoll-stagec3/htdocs/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('sprout-base-rep...', Array)
#10 /srv/app/nttmcoll-stagec3/htdocs/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#11 /srv/app/nttmcoll-stagec3/htdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#12 /srv/app/nttmcoll-stagec3/htdocs/web/index.php(23): yii\base\Application->run()
#13 {main}
```

This is because I think the start and end date value is expected by the Service class, but it isn't a mandatory field on the report field layout, so by the plugin CP this allowed and in Craft 2 you could do this without any issues.

The easiest fixed would be fallback to the current DateTime at the time of the export if start and end time is not set, so it can generate the file with some form of date value.

### Steps to reproduce

1. Create a Sprout Report without a start and end date defined
2. Export it and get this error

### Additional info

- Craft version: 3.5.19
- PHP version: 7.4
- Database driver & version:  MySQL 8

**Comment by BenParizek** [comment]
Thanks @jamesmacwhite. 

I'm currently focused on getting our plugin migration workflow back in order but will circle back to this once I have the chance and let you know once it's resolved.

**Comment by jamesmacwhite** [comment]
@BenParizek Thanks Ben. Totally understand, I'm also keen for the Craft 2 -> 3 migration track being updated as there's a couple of migrations with Sprout Reports that are blocking a Craft 2 -> 3 migration currently for us.
