### ISSUE TITLE
Composer errors when trying to update from 1.2.11

### ISSUE THREAD

**Issue by brettburwell** [barrelstrength/craft-sprout-reports#93]
### Description
When trying to update from Sprout Reports version 1.2.11 I'm seeing the following composer errors: 

```html
Problem 1
- Installation request for barrelstrength/sprout-reports 1.5.6 -> satisfiable by barrelstrength/sprout-reports[1.5.6].
- Conclusion: don't install barrelstrength/sprout-base 5.2.0
- barrelstrength/sprout-forms 3.6.8 requires barrelstrength/sprout-base ^5.0.8 -> satisfiable by barrelstrength/sprout-base[5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0].
- barrelstrength/sprout-forms 3.6.8 requires barrelstrength/sprout-base ^5.0.8 -> satisfiable by barrelstrength/sprout-base[5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0].
- barrelstrength/sprout-forms 3.6.8 requires barrelstrength/sprout-base ^5.0.8 -> satisfiable by barrelstrength/sprout-base[5.0.9, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0].
- Can only install one of: barrelstrength/sprout-base[6.0.0, 5.0.9].
- Can only install one of: barrelstrength/sprout-base[5.0.9, 6.0.0].
- Can only install one of: barrelstrength/sprout-base[5.1.0, 6.0.0].
- Can only install one of: barrelstrength/sprout-base[5.1.1, 6.0.0].
- Can only install one of: barrelstrength/sprout-base[5.1.2, 6.0.0].
- Can only install one of: barrelstrength/sprout-base[5.1.3, 6.0.0].
- Can only install one of: barrelstrength/sprout-base[6.0.0, 5.0.9].
- barrelstrength/sprout-reports 1.5.6 requires barrelstrength/sprout-base ^6.0.0 -> satisfiable by barrelstrength/sprout-base[6.0.1, 6.0.0].
- Conclusion: don't install barrelstrength/sprout-base 6.0.1
- Installation request for barrelstrength/sprout-forms (locked at 3.6.8, required as ^3.5) -> satisfiable by barrelstrength/sprout-forms[3.6.8].
```

My primary issue / need for updating is related to Issue #75, so I tried updating incrementally to 1.3.0 hoping that would get the plugin up and running for my client again. But when doing so I saw this error: 
```
- Installation request for barrelstrength/sprout-reports 1.3.0 -> satisfiable by barrelstrength/sprout-reports[1.3.0].
- Conclusion: remove barrelstrength/sprout-base 5.0.9
- barrelstrength/sprout-reports 1.3.0 requires barrelstrength/sprout-base ^5.1.0 -> satisfiable by barrelstrength/sprout-base[5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.2.0].
- Can only install one of: barrelstrength/sprout-base[5.1.0, 5.0.9].
- Can only install one of: barrelstrength/sprout-base[5.1.1, 5.0.9].
- Can only install one of: barrelstrength/sprout-base[5.1.2, 5.0.9].
- Can only install one of: barrelstrength/sprout-base[5.1.3, 5.0.9].
- Can only install one of: barrelstrength/sprout-base[5.2.0, 5.0.9].
- Installation request for barrelstrength/sprout-base (installed at 5.0.9) -> satisfiable by barrelstrength/sprout-base[5.0.9].
```

As a test, I also tried uninstalling the plugins entirely and reinstalling from scratch. Doing so resulted in the following errors:
```
- barrelstrength/sprout-reports 1.5.6 requires barrelstrength/sprout-base-reports ^1.5.6 -> satisfiable by barrelstrength/sprout-base-reports[1.5.6].
- Conclusion: don't install barrelstrength/sprout-base-reports 1.5.6
- barrelstrength/sprout-reports 1.5.5 requires barrelstrength/sprout-base-reports ^1.5.5 -> satisfiable by barrelstrength/sprout-base-reports[1.5.5, 1.5.6].
- Conclusion: don't install barrelstrength/sprout-base-reports 1.5.5
- Conclusion: don't install barrelstrength/sprout-reports 1.5.4
- Conclusion: don't install barrelstrength/sprout-reports 1.5.3
- Conclusion: don't install barrelstrength/sprout-reports 1.5.2
- Conclusion: don't install barrelstrength/sprout-reports 1.5.1
- Conclusion: remove barrelstrength/sprout-base 5.0.9
- Installation request for barrelstrength/sprout-base-reports (locked at 1.3.10) -> satisfiable by barrelstrength/sprout-base-reports[1.3.10].
- Installation request for barrelstrength/sprout-reports ^1.5 -> satisfiable by barrelstrength/sprout-reports[1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6].
- Conclusion: don't install barrelstrength/sprout-base 5.0.9
- barrelstrength/sprout-reports 1.5.0 requires barrelstrength/sprout-base ^6.0.0 -> satisfiable by barrelstrength/sprout-base[6.0.0, 6.0.1].
- Can only install one of: barrelstrength/sprout-base[6.0.0, 5.0.9].
- Can only install one of: barrelstrength/sprout-base[6.0.1, 5.0.9].
- Installation request for barrelstrength/sprout-base (locked at 5.0.9) -> satisfiable by barrelstrength/sprout-base[5.0.9].
```
Any guidance on how to move forward would be much appreciated. Because of the issue mentioned in #75 my client isn't able to access reports they need for their internal accounting at the moment. 

### Additional info
- Craft version: 3.4.22.1
- PHP version: 7.2
- Database driver & version:  MySQL 5.7.30

### Installed Sprout Plugins
- Sprout Email: 4.0.6
- Sprout Fields: 3.5.1
- Sprout Forms: 3.6.8
- Sprout Notes: 2.2.3
- Sprout Reports: 1.2.11
- Sprout Reports (Commerce Data Source): 1.0.1

**Comment by BenParizek** [comment]
@brettburwell I believe the issue here may be that you have two different Sprout plugins installed and they both have a dependency that had a major version release, so it won't be possible to update one before the other, all of them will have to be updated at once.

That said, your inclination to try to reinstall things from scratch was a good one, however, the error message there seems to say `barrelstrength/sprout-base (locked at 5.0.9)`. Usually, "locked at" means that you still have a `composer.lock` file in your project that might be telling composer to not upgrade past a particular version.

So, could you try:

1. Delete `/vendor` AND `/composer.lock`
2. Make sure you have the latest plugin versions referenced in your `composer.json`
2. Re-run `composer update`

**Comment by brettburwell** [comment]
Hi @BenParizek. Thanks for the response. When I follow those steps I see the following error: 
```
Database Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'sproutreports.users'
The SQL being executed was: ALTER TABLE craft_sproutreports_reports CHANGE dataSourceId dataSourceId int(11)

Migration: barrelstrength\sproutreports\migrations\m200520_000002_update_datasourceId_column_type_sproutreports

Output:

> alter column dataSourceId in table {{%sproutreports_reports}} to integer ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'sproutreports.users'
The SQL being executed was: ALTER TABLE craft_sproutreports_reports CHANGE dataSourceId dataSourceId int(11) (/Users/bburwell/Documents/Sites/Mighty Few/revbrew/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /path/to/project/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /path/to/project/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /path/to/project/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /path/to/project/vendor/barrelstrength/sprout-base-reports/src/migrations/m200520_000002_update_datasourceId_column_type.php(25): yii\db\Migration->alterColumn('{{%sproutreport...', 'dataSourceId', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /path/to/project/vendor/barrelstrength/sprout-reports/src/migrations/m200520_000002_update_datasourceId_column_type_sproutreports.php(18): barrelstrength\sproutbasereports\migrations\m200520_000002_update_datasourceId_column_type->safeUp()
#5 /path/to/project/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutreports\migrations\m200520_000002_update_datasourceId_column_type_sproutreports->safeUp()
#6 /path/to/project/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /path/to/project/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutreports\migrations\m200520_000002_update_datasourceId_column_type_sproutreports))
#8 /path/to/project/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#9 /path/to/project/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#10 /path/to/project/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /path/to/project/revbrew/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /path/to/project/revbrew/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /path/to/project/revbrew/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#15 /path/to/project/revbrew/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /path/to/project/revbrew/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#17 /path/to/project/revbrew/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#18 /path/to/project/revbrew/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /path/to/project/revbrew/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /path/to/project/revbrew/public/index.php(21): yii\base\Application->run()
#21 /Users/foo/.composer/vendor/laravel/valet/server.php(158): require('/Users/bburwell...')
#22 {main}
```

It looks like that might be similar to [Sprout Forms Issue 495](https://github.com/barrelstrength/craft-sprout-forms/issues/492).

**Comment by brettburwell** [comment]
@BenParizek Quick followup. I was able to get around the migration issue by just deleting all the rows of the `craft_sproutreports_reports` table before updating and recreating the reports after the updates and migrations ran. 

Not ideal, but it looks like everything is back up and running again. Thanks again for the quick reply this morning.
