### ISSUE TITLE
Migration from craft 2 to craft 3: unknown property sortOrder

### ISSUE THREAD

**Issue by krizzzly** [barrelstrength/craft-sprout-reports#95]
### Description (screenshots, logs, ...)

Error Message: 
```
Yii Migration Tool (based on Yii v2.0.35)

Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating Sprout Reports.'

in /www/craft3/vendor/craftcms/cms/src/services/Updates.php:241

Stack trace:
#0 /www/craft3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(260): craft\services\Updates->runMigrations(Array)
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /www/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#3 /www/craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 /www/craft3/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction('all', Array)
#5 /www/craft3/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('all', Array)
#6 /www/craft3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#7 /www/craft3/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction('migrate/all', Array)
#8 /www/craft3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#9 /www/craft3/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#10 /www/craft3/craft(23): yii\base\Application->run()
#11 {main}

```

### Steps to reproduce

1. craft 2 installation with sprout reports 0.10.1 installed
2. migrate to craft 3
3. install craft 3 version of the plugin

```
$ composer require barrelstrength/sprout-reports
$ ./craft install/plugin sprout-reports
$ ./craft migrate/all
```

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3434d)

**Comment by krizzzly** [comment]
when running the migration from accessing the control panel via browser i get this printed:

```
Exception: Setting unknown property: barrelstrength\sproutbasereports\records\Report::sortOrder 

(/www/craft3/vendor/yiisoft/yii2/base/Component.php:209)
#0 /www/craft3/vendor/yiisoft/yii2/db/BaseActiveRecord.php(324): yii\base\Component->__set('sortOrder', NULL)
#1 /www/craft3/vendor/craftcms/cms/src/db/ActiveRecord.php(41): yii\db\BaseActiveRecord->__set('sortOrder', NULL)
#2 /www/craft3/vendor/barrelstrength/sprout-base-reports/src/elements/Report.php(500): craft\db\ActiveRecord->__set('sortOrder', NULL)
#3 /www/craft3/vendor/craftcms/cms/src/services/Elements.php(2172): barrelstrength\sproutbasereports\elements\Report->afterSave(true)
#4 /www/craft3/vendor/craftcms/cms/src/services/Elements.php(532): craft\services\Elements->_saveElementInternal(Object(barrelstrength\sproutbasereports\elements\Report), false, false, true)
#5 /www/craft3/vendor/barrelstrength/sprout-base-reports/src/migrations/m190305_000002_update_record_to_element_types.php(60): craft\services\Elements->saveElement(Object(barrelstrength\sproutbasereports\elements\Report), false)
#6 /www/craft3/vendor/barrelstrength/sprout-reports/src/migrations/m190305_000002_update_record_to_element_types_sproutreports.php(32): barrelstrength\sproutbasereports\migrations\m190305_000002_update_record_to_element_types->safeUp()
#7 /www/craft3/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutreports\migrations\m190305_000002_update_record_to_element_types_sproutreports->safeUp()
#8 /www/craft3/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#9 /www/craft3/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutreports\migrations\m190305_000002_update_record_to_element_types_sproutreports))
#10 /www/craft3/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#11 /www/craft3/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#12 /www/craft3/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#13 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#14 /www/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /www/craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /www/craft3/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#17 /www/craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#18 /www/craft3/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#19 /www/craft3/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#20 /www/craft3/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#21 /www/craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /www/craft3/public/index.php(22): yii\base\Application->run()
#23 {main}
```

**Comment by krizzzly** [comment]
i started manually fixing the migrations, and a couple of more issues appeared after fixing the previous one:

![Bildschirmfoto 2020-08-03 um 11 17 48](https://user-images.githubusercontent.com/48832704/89167012-2663f480-d57b-11ea-9d8e-9e6343f5d563.png)

this column in table `sproutreports_reports` is altered to type integer, which will fail because it has content.
On the other hand, there are no datasources in new table `sproutreports_datasources` that could match these strings.

**Comment by BenParizek** [comment]
Thanks @krizzzly. We're working on a migration to get this resolved.

If you need to fix this manually, you might be able to update those values to the Data Source IDs before the migration. I'll update this thread when we have a fix.

**Comment by BenParizek** [comment]
This migration issue should be addressed in the latest release of Sprout Reports. 

I'm catching up on several support tickets right now and working on a large update to improve the migration process that has been causing a lot of issues in our plugins. There will likely be several smaller updates coming out over the next couple of weeks so, if possible, I'd recommend holding off on updating until we get Sprout Reports v2.0 out the door which should get things into a lot better shape and address a number of smaller issues all at once.
