### ISSUE TITLE
Unknown column sproutreports_reports.delimiter

### ISSUE THREAD

**Issue by benjaminkohl** [barrelstrength/craft-sprout-reports#97]
### Description

We have v1.5.1 installed which _was_ working. It _didn't_ get updated beyond that then one day our client was no longer able to access the plugin because of a server error.

The error I saw in the log was:

```
2020-07-29 16:52:28 [-][287][88dnjaqemtc3cj6ibb33ngrhlc][error][yii\db\Exception] PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sproutreports_reports.delimiter' in 'field list' in /path/to/site/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /path/to/site/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /path/to/site/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute()
#2 /path/to/site/vendor/yiisoft/yii2/db/Command.php(427): yii\db\Command->queryInternal()
#3 /path/to/site/vendor/yiisoft/yii2/db/Query.php(433): yii\db\Command->queryScalar()
#4 /path/to/site/vendor/craftcms/cms/src/db/Query.php(214): yii\db\Query->exists()
#5 /path/to/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1520): craft\db\Query->exists()
#6 /path/to/site/vendor/twig/twig/src/Extension/CoreExtension.php(1499): craft\elements\db\ElementQuery->exists()
#7 /path/to/site/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute()
#8 /path/to/site/storage/runtime/compiled_templates/c4/c459ccf50fb90ea306c9a6cb5caf5f97a65826e97010dc9758ef78c64a229e49.php(125): craft\helpers\Template::attribute()
#9 /path/to/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a9108b163c9dfe2449f4b85d672e51084832aea7bd28476bd93ae601d267227b->doDisplay()
#10 /path/to/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#11 /path/to/site/storage/runtime/compiled_templates/a6/a60404c163e18af7fe271e22c86f0587ccfe0ff5d8a93f12c4a88c68436e6191.php(141): Twig\Template->display()
#12 /path/to/site/vendor/twig/twig/src/Template.php(184): __TwigTemplate_0825217f75664d17dd83a8250b79ced6ff43737c7623faa3a055f5477b3d869b->block_toolbar()
#13 /path/to/site/vendor/twig/twig/src/Template.php(256): Twig\Template->displayBlock()
#14 /path/to/site/storage/runtime/compiled_templates/0c/0cf5327f094cc1542ce3deeb22fcc349befbbac04c3b7d34973afd50234dd91c.php(95): Twig\Template->renderBlock()
#15 /path/to/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_b0b035de9d98390b55cdf17952f5691a6ed940909042161f8b9fa9de16636117->doDisplay()
#16 /path/to/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#17 /path/to/site/storage/runtime/compiled_templates/a6/a60404c163e18af7fe271e22c86f0587ccfe0ff5d8a93f12c4a88c68436e6191.php(72): Twig\Template->display()
#18 /path/to/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_0825217f75664d17dd83a8250b79ced6ff43737c7623faa3a055f5477b3d869b->doDisplay()
#19 /path/to/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#20 /path/to/site/storage/runtime/compiled_templates/bc/bc0628ef3660d523442486186af0caa723a1037c91f44a0985c6105679b3ab10.php(46): Twig\Template->display()
#21 /path/to/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f5807938d7314b0b16bd6cc550b164ea10ba0083f9397337f930efc6161de367->doDisplay()
#22 /path/to/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#23 /path/to/site/storage/runtime/compiled_templates/66/666f6c7a520b6bad37d728e79be3c4b0d86f22f03c73c09dc3eb2ce188a999fa.php(53): Twig\Template->display()
#24 /path/to/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_9fc3125790a5755d1a8d1b38bdba5b98cabb6a1b570671311655304fe06f7c6e->doDisplay()
#25 /path/to/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling()
#26 /path/to/site/vendor/twig/twig/src/Template.php(392): Twig\Template->display()
#27 /path/to/site/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#28 /path/to/site/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render()
#29 /path/to/site/vendor/craftcms/cms/src/web/View.php(397): Twig\Environment->render()
#30 /path/to/site/vendor/craftcms/cms/src/web/View.php(458): craft\web\View->renderTemplate()
#31 /path/to/site/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate()
#32 /path/to/site/vendor/barrelstrength/sprout-base-reports/src/controllers/ReportsController.php(118): craft\web\Controller->renderTemplate()
#33 [internal function]: barrelstrength\sproutbasereports\controllers\ReportsController->actionReportsIndexTemplate()
#34 /path/to/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#35 /path/to/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#36 /path/to/site/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#37 /path/to/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#38 /path/to/site/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#39 /path/to/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#40 /path/to/site/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest()
#41 /path/to/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#42 /path/to/site/public/index.php(24): yii\base\Application->run()
#43 {main}
```

So I tried updating to v1.5.6 to see if that would fix the issue but I got migration errors so I could not complete the update.

```
Database Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'sproutreports.users'
The SQL being executed was: ALTER TABLE craft_sproutreports_reports CHANGE dataSourceId dataSourceId int(11)

Migration: barrelstrength\sproutreports\migrations\m200520_000002_update_datasourceId_column_type_sproutreports

Output:

> alter column dataSourceId in table {{%sproutreports_reports}} to integer ...Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: 'sproutreports.users'
The SQL being executed was: ALTER TABLE craft_sproutreports_reports CHANGE dataSourceId dataSourceId int(11) (/path/to/site/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /path/to/site/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException()
#1 /path/to/site/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute()
#2 /path/to/site/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /path/to/site/vendor/barrelstrength/sprout-base-reports/src/migrations/m200520_000002_update_datasourceId_column_type.php(25): yii\db\Migration->alterColumn()
#4 /path/to/site/vendor/barrelstrength/sprout-reports/src/migrations/m200520_000002_update_datasourceId_column_type_sproutreports.php(18): barrelstrength\sproutbasereports\migrations\m200520_000002_update_datasourceId_column_type->safeUp()
#5 /path/to/site/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutreports\migrations\m200520_000002_update_datasourceId_column_type_sproutreports->safeUp()
#6 /path/to/site/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up()
#7 /path/to/site/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp()
#8 /path/to/site/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#9 /path/to/site/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations()
#10 /path/to/site/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations()
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /path/to/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#13 /path/to/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#14 /path/to/site/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#15 /path/to/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#16 /path/to/site/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#17 /path/to/site/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction()
#18 /path/to/site/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic()
#19 /path/to/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#20 /path/to/site/public/index.php(24): yii\base\Application->run()
#21 {main}
```

I rolled the plugin back to 1.5.1 and now suddenly it works. This is the umpteenth time that this plugin has managed to break itself on one of our clients' sites. Any idea what happened?

### Additional info

- Craft version: 3.4.11
- PHP version: 7.4.9
- Database driver & version:  MySQL 5.5.5
- Plugins & versions: 1.5.1 | 1.5.6

**Comment by BenParizek** [comment]
@benjaminkohl I'm working on a new major release for Craft 3.5 that will address the ongoing migration issues.

The short version is that a while back a made an architectural decision to break out some shared Sprout functionality (including reports) into multiple composer packages. As time went on, with additional releases in various plugins we have that use the shared functionality, the complexity around this decision multiplied and at some point seemed to get exponential in the number of minor outlier and migration issues it created between the various plugins using the shared modules.

I've spent the last couple of months working on a new major release that consolidates all of the shared modules into a single package again. That is mostly done and I'm currently working through the migrations needed to try to get things back on track and less burdensome again.

While I do consider this a high priority, it's taking some time to get right as the update isn't simply about a single column in a db migration but the entire architecture of the Sprout plugins right now. Once I get through that, our issues should become more specific to what they appear to be about again.

**Comment by BenParizek** [comment]
This migration issue should be addressed in the latest release of Sprout Reports. 

I'm catching up on several support tickets right now and working on a large update to improve the migration process that has been causing a lot of issues in our plugins. There will likely be several smaller updates coming out over the next couple of weeks so, if possible, I'd recommend holding off on updating until we get Sprout Reports v2.0 out the door which should get things into a lot better shape and address a number of smaller issues all at once.
